"use client";
import { useEffect,useState } from "react";
import type { CourseClient,DocumentRevision,RevisionProposal } from "@/lib/course-client";
import { formatShanghaiDateTime } from "@/lib/time.mjs";
type Deck={title:string;slides:Array<{slideId:string;title:string;speakerNotes:string;layout:string;blocks:unknown[]}>};
export function DeckRevisionEditor({client,projectId,onArtifactsChanged}:{client:CourseClient;projectId?:string;onArtifactsChanged:()=>void}){
 const [history,setHistory]=useState<DocumentRevision[]>([]),[active,setActive]=useState<DocumentRevision>(),[deck,setDeck]=useState<Deck>(),[slide,setSlide]=useState(0),[draft,setDraft]=useState(""),[notes,setNotes]=useState(""),[instruction,setInstruction]=useState(""),[snapshot,setSnapshot]=useState(""),[proposal,setProposal]=useState<RevisionProposal>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{if(!projectId||client.mode!=="online")return;setBusy(true);setError("");try{const list=await client.listDocumentRevisions(projectId,"deck");const current=list.revisions.find(r=>r.revisionId===list.activeRevisionId);if(!current)throw new Error("没有活动 Deck 修订");const content=await client.getRevisionContent(projectId,"deck",current.revisionId);const value=content.document as Deck;setHistory(list.revisions);setActive(current);setDeck(value);setDraft(value.slides[slide]?.title??"");setNotes(value.slides[slide]?.speakerNotes??"");}catch(e){setError(e instanceof Error?e.message:"修订读取失败");}finally{setBusy(false)}};
 useEffect(()=>{void load()},[projectId,client]);useEffect(()=>{setDraft(deck?.slides[slide]?.title??"");setNotes(deck?.slides[slide]?.speakerNotes??"")},[slide,deck]);
 const propose=async(mode:"manual"|"ai")=>{if(!projectId||!active)return;setBusy(true);setError("");try{const patch=mode==="manual"?[{op:"replace" as const,path:`/slides/${slide}/title`,value:draft},{op:"replace" as const,path:`/slides/${slide}/speakerNotes`,value:notes}]:undefined;setProposal(await client.createRevisionProposal(projectId,{kind:"deck",baseRevisionId:active.revisionId,baseContentHash:active.contentHash,mode,patch,...(mode==="ai"?{instruction,configurationSnapshotId:snapshot}:{})}));}catch(e){setError(e instanceof Error?e.message:"修改建议生成失败");}finally{setBusy(false)}};
 const apply=async()=>{if(!projectId||!proposal)return;setBusy(true);try{await client.applyRevisionProposal(projectId,proposal.proposalId);setProposal(undefined);await load();onArtifactsChanged();}catch(e){setError(e instanceof Error?e.message:"应用失败");setBusy(false)}};
 const restore=async(revisionId:string)=>{if(!projectId||!active)return;setBusy(true);try{await client.restoreDocumentRevision(projectId,"deck",{revisionId,baseRevisionId:active.revisionId,baseContentHash:active.contentHash});await load();onArtifactsChanged();}catch(e){setError(e instanceof Error?e.message:"恢复失败");setBusy(false)}};
 const toggleLock=async(path:string)=>{if(!projectId||!active)return;setBusy(true);try{const exists=active.locks.some(lock=>lock.locked&&lock.path===path);await client.updateRevisionLocks(projectId,"deck",{baseRevisionId:active.revisionId,baseContentHash:active.contentHash,locks:[...active.locks.filter(lock=>lock.path!==path),{path,locked:!exists}]});await load();}catch(e){setError(e instanceof Error?e.message:"锁定失败");setBusy(false)}};
 if(client.mode!=="online")return <div className="revision-empty">演示模式不会伪造在线 Deck、AI 修改或版本历史。</div>;if(!projectId)return <div className="revision-empty">请先创建项目并生成真实 DeckSpec。</div>;if(error&&!deck)return <div className="revision-empty error">{error}<button onClick={()=>void load()}>重试</button></div>;if(!deck||!active)return <div className="revision-empty">{busy?"正在读取真实 DeckSpec…":"没有可编辑的 DeckSpec 产物"}</div>;
 const titlePath=`/slides/${slide}/title`,notesPath=`/slides/${slide}/speakerNotes`;const titleLocked=active.locks.some(l=>l.locked&&l.path===titlePath),notesLocked=active.locks.some(l=>l.locked&&l.path===notesPath); return <div className="revision-editor"><aside><header><b>真实页面树</b><small>r{active.revision}</small></header>{deck.slides.map((s,i)=><button className={i===slide?"active":""} key={s.slideId} onClick={()=>setSlide(i)}><span>{i+1}</span><p>{s.title}</p></button>)}<h4>不可变历史</h4>{history.map(r=><div className="revision-item" key={r.revisionId}><b>r{r.revision} · {r.reason}</b><time>{formatShanghaiDateTime(r.createdAt)}</time>{r.revisionId!==active.revisionId&&<button disabled={busy} onClick={()=>void restore(r.revisionId)}>恢复为新版本</button>}</div>)}</aside><section><header><b>{deck.slides[slide]?.slideId}</b><span>{active.mediaState==="stale_requires_regeneration"?"TTS/视频已过期，需重新生成":"媒体状态正常"}</span></header><label>标题 <button onClick={()=>void toggleLock(titlePath)}>{titleLocked?"解锁":"锁定"}</button><input disabled={titleLocked} value={draft} onChange={e=>setDraft(e.target.value)}/></label><label>讲稿 <button onClick={()=>void toggleLock(notesPath)}>{notesLocked?"解锁":"锁定"}</button><textarea disabled={notesLocked} rows={10} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="primary" disabled={busy} onClick={()=>void propose("manual")}>预览字段修改</button>{error&&<p className="revision-error">{error}</p>}</section><aside className="revision-ai"><h3>AI 局部修改</h3><p>AI 只返回受限 JSON Patch；不会直接写入，需确认后应用。</p><textarea rows={6} value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="例如：让本页讲稿更适合年轻研发人员"/><input value={snapshot} onChange={e=>setSnapshot(e.target.value)} placeholder="已发布配置快照 UUID"/><button disabled={busy||!instruction||!snapshot} onClick={()=>void propose("ai")}>生成 AI Diff</button>{proposal&&<div className="revision-diff"><b>待确认 Diff</b>{proposal.patch.map((p,i)=><code key={i}>{p.op} {p.path}{p.value!==undefined?` → ${JSON.stringify(p.value)}`:""}</code>)}<button className="primary" disabled={busy} onClick={()=>void apply()}>确认并应用</button><button onClick={()=>setProposal(undefined)}>放弃</button></div>}</aside></div>;
}
