import assert from "node:assert/strict";
import test from "node:test";
import { AUDIO_MASTERING_TARGET, allocateSentenceTargets, buildMeasuredDurationManifest, concatenatePcm16Wav, decideDurationCorrection, inspectWav, renderSrt, renderWebVtt, segmentChineseNarration, validateMeasuredWavDuration } from "./index.js";

test("segments Chinese narration deterministically and keeps punctuation with closing quotes",()=>{const script="第一句。\r\n“真的安全吗？” 下一句……\n最后一句";assert.deepEqual(segmentChineseNarration(script),["第一句。","“真的安全吗？”","下一句……","最后一句"]);assert.deepEqual(segmentChineseNarration(script),segmentChineseNarration(script));});
test("allocates exact target duration with deterministic sentence ids",()=>{const result=allocateSentenceTargets("短句。这里是一句明显更长的讲解。",10000);assert.equal(result.reduce((sum,item)=>sum+item.targetDurationMs,0),10000);assert.ok(result[1]!.targetDurationMs>result[0]!.targetDurationMs);assert.match(result[0]!.sentenceId,/^sentence-[a-f0-9]{16}$/);});
test("measured manifest uses audio durations and emits valid VTT and SRT",()=>{const sentences=allocateSentenceTargets("先核验。再操作。",4000),hash="a".repeat(64);const manifest=buildMeasuredDurationManifest(sentences,sentences.map((sentence,index)=>({sentenceId:sentence.sentenceId,uri:`local://audio/${index}.wav`,durationMs:index?2100:1900,contentHash:hash})));assert.equal(manifest.totalMeasuredDurationMs,4000);assert.deepEqual(manifest.sentences.map(item=>[item.startsAtMs,item.endsAtMs]),[[0,1900],[1900,4000]]);assert.match(renderWebVtt(manifest),/^WEBVTT\n\n00:00:00\.000 --> 00:00:01\.900/u);assert.match(renderSrt(manifest),/^1\n00:00:00,000 --> 00:00:01,900/u);});
test("duration policy limits atempo to 5 percent and TTS speed to 0.90-1.10",()=>{assert.equal(decideDurationCorrection(10000,10050).action,"accept");assert.deepEqual(decideDurationCorrection(10000,9600).action,"pad_silence");const atempo=decideDurationCorrection(10000,10400);assert.equal(atempo.action,"atempo");assert.equal(atempo.speed,1.04);const speed=decideDurationCorrection(10000,10800);assert.equal(speed.action,"tts_speed");assert.equal(speed.speed,1.08);assert.equal(decideDurationCorrection(10000,12000).action,"rewrite");assert.match(decideDurationCorrection(10000,8800).rewriteHint??"",/补充讲稿/u);});

function wav(durationMs:number,sampleRate=16000):Buffer{const frames=Math.round(durationMs/1000*sampleRate),dataBytes=frames*2,bytes=Buffer.alloc(44+dataBytes);bytes.write("RIFF",0);bytes.writeUInt32LE(36+dataBytes,4);bytes.write("WAVE",8);bytes.write("fmt ",12);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(sampleRate,24);bytes.writeUInt32LE(sampleRate*2,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write("data",36);bytes.writeUInt32LE(dataBytes,40);return bytes;}
test("validates WAV metadata and manifest duration without claiming loudness measurement",()=>{const bytes=wav(1250);assert.deepEqual(inspectWav(bytes),{format:"pcm",channels:1,sampleRateHz:16000,bitsPerSample:16,blockAlign:2,dataBytes:40000,sampleFrames:20000,durationMs:1250});assert.equal(validateMeasuredWavDuration(bytes,1260,10).durationMs,1250);assert.throws(()=>validateMeasuredWavDuration(bytes,1300,20),/does not match/u);const broken=Buffer.from(bytes);broken.writeUInt32LE(1,28);assert.throws(()=>inspectWav(broken),/inconsistent/u);assert.equal(AUDIO_MASTERING_TARGET.integratedLufs,-16);assert.equal(AUDIO_MASTERING_TARGET.maxTruePeakDbtp,-1);assert.match(AUDIO_MASTERING_TARGET.description,/does not claim/u);});
test("concatenates PCM16 WAV samples and rewrites RIFF lengths from actual data",()=>{const joined=concatenatePcm16Wav([wav(250),wav(750)]);assert.equal(joined.metadata.durationMs,1000);assert.equal(joined.metadata.sampleFrames,16000);const view=new DataView(joined.bytes.buffer,joined.bytes.byteOffset,joined.bytes.byteLength);assert.equal(view.getUint32(4,true)+8,joined.bytes.byteLength);assert.equal(view.getUint32(40,true),32000);assert.equal(inspectWav(joined.bytes).durationMs,1000);});
test("PCM concatenation rejects bad headers and incompatible formats without resampling",()=>{const bad=wav(100);bad.write("NOPE",0);assert.throws(()=>concatenatePcm16Wav([bad]),/RIFF/u);assert.throws(()=>concatenatePcm16Wav([wav(100,16000),wav(100,24000)]),/identical sample rate/u);const inconsistent=wav(100);inconsistent.writeUInt32LE(inconsistent.readUInt32LE(4)-2,4);assert.throws(()=>concatenatePcm16Wav([inconsistent]),/RIFF length/u);});
