import assert from "node:assert/strict";
import test from "node:test";
import { buildVideoTimeline,createFfmpegRenderPlan,validateMp4Artifact,type RenderManifestInput,type SpeechManifestInput } from "./video.js";

const render:RenderManifestInput={schemaVersion:"1",renderId:"render-1",width:1920,height:1080,fps:30,output:{container:"mp4",videoCodec:"h264",pixelFormat:"yuv420p",audioCodec:"aac"},segments:[{slideId:"intro",order:0,durationMs:1000,audioUri:"artifact://intro",transition:"fade",sourceHash:"a"},{slideId:"rules",order:1,durationMs:1500,audioUri:"artifact://rules",transition:"slide",sourceHash:"b"}]};
const speech:SpeechManifestInput={totalMeasuredDurationMs:2500,sentences:[{startsAtMs:0,endsAtMs:900},{startsAtMs:900,endsAtMs:2500}]};
test("builds deterministic page frames and versioned adjacent transition intervals",()=>{const timeline=buildVideoTimeline(render,speech);assert.equal(timeline.schemaVersion,"2");assert.equal(timeline.renderMode,"final-static-xfade-v1");assert.equal(timeline.totalFrames,75);assert.deepEqual(timeline.segments.map(s=>({first:s.firstFrame,count:s.frameCount,start:s.startsAtMs,end:s.endsAtMs})),[{first:0,count:30,start:0,end:1000},{first:30,count:45,start:1000,end:2500}]);assert.deepEqual(timeline.transitions,[{schemaVersion:"1",boundaryOrder:0,fromSlideId:"intro",toSlideId:"rules",kind:"slideleft",startsAtMs:1000,endsAtMs:1300,durationMs:300,firstFrame:30,frameCount:9}]);assert.deepEqual(buildVideoTimeline(render,speech),timeline);});
test("rejects timeline gaps and mismatched measured duration",()=>{assert.throws(()=>buildVideoTimeline({...render,segments:[render.segments[0]!,{...render.segments[1]!,order:3}]},speech),/contiguous/u);assert.throws(()=>buildVideoTimeline(render,{...speech,totalMeasuredDurationMs:2400}),/durations disagree/u);assert.throws(()=>buildVideoTimeline(render,{...speech,sentences:[{startsAtMs:1,endsAtMs:2500}]}),/contiguous/u);});
test("creates an argv-only constrained xfade video and non-overlapped audio plan",()=>{const plan=createFfmpegRenderPlan({render,speech,slideImages:{intro:"slide-001.png",rules:"slide-002.png"},slideAudio:{intro:"audio-001.wav",rules:"audio-002.wav"},outputFilename:"course-final.mp4"});assert.equal(plan.executable,"ffmpeg");assert.equal(plan.outputPath,"work/course-final.mp4");assert.match(plan.filterComplex,/xfade=transition=slideleft:duration=0\.300000000:offset=1\.000000000/u);assert.match(plan.filterComplex,/\[a0\]\[a1\]concat=n=2:v=0:a=1\[aout\]/u);assert.match(plan.filterComplex,/trim=end_frame=39/u);assert.ok(plan.args.includes("work/slide-001.png"));assert.ok(plan.args.includes("work/audio-002.wav"));assert.deepEqual(plan.args.slice(-4),["+faststart","-f","mp4","work/course-final.mp4"]);});
test("ceil-quantizes non-integral narration without trimming its tail",()=>{const nonIntegralRender={...render,segments:[{...render.segments[0]!,durationMs:1001},{...render.segments[1]!,durationMs:1333}]};const nonIntegralSpeech={totalMeasuredDurationMs:2334,sentences:[{startsAtMs:0,endsAtMs:1001},{startsAtMs:1001,endsAtMs:2334}]};const plan=createFfmpegRenderPlan({render:nonIntegralRender,speech:nonIntegralSpeech,slideImages:{intro:"slide-001.png",rules:"slide-002.png"},slideAudio:{intro:"audio-001.wav",rules:"audio-002.wav"},outputFilename:"quantized.mp4"});assert.equal(plan.timeline.speechDurationMs,2334);assert.deepEqual(plan.timeline.segments.map(item=>item.frameCount),[31,40]);assert.equal(plan.timeline.totalFrames,71);assert.equal(plan.timeline.totalDurationMs,71*1000/30);assert.ok(plan.timeline.segments.every(item=>item.durationMs>=item.measuredDurationMs));assert.match(plan.filterComplex,/apad=whole_dur=1\.033333333,atrim=end=1\.033333333/u);assert.match(plan.filterComplex,/trim=end_frame=40,settb=AVTB/u);assert.match(plan.filterComplex,/\[vx1\]trim=end_frame=71/u);assert.equal(plan.args[plan.args.indexOf("-frames:v")+1],"71");});
test("blocks path and argument injection before producing a command plan",()=>{const base={render,speech,slideImages:{intro:"slide-001.png",rules:"slide-002.png"},slideAudio:{intro:"audio-001.wav",rules:"audio-002.wav"},outputFilename:"safe.mp4"};for(const hostile of ["../x.png","x;touch.png","-option.png","nested/x.png"]){assert.throws(()=>createFfmpegRenderPlan({...base,slideImages:{...base.slideImages,intro:hostile}}),/controlled work directory/u);}assert.throws(()=>createFfmpegRenderPlan({...base,outputFilename:"-f.mp4"}),/unsafe/u);assert.throws(()=>createFfmpegRenderPlan({...base,outputFilename:"../x.mp4"}),/unsafe/u);});
test("final transition policy maps Reveal effects to its allowlist and rejects unsafe durations or short pages",()=>{assert.equal(buildVideoTimeline({...render,segments:[render.segments[0]!,{...render.segments[1]!,transition:"zoom"}]},speech).transitions[0]?.kind,"fade");assert.throws(()=>buildVideoTimeline({...render,segments:[render.segments[0]!,{...render.segments[1]!,transition:"wipe" as never}]},speech),/allowlist/u);assert.throws(()=>buildVideoTimeline(render,speech,501),/250-500/u);const shortRender={...render,segments:[{...render.segments[0]!,durationMs:250},{...render.segments[1]!,durationMs:250}]};const shortSpeech={totalMeasuredDurationMs:500,sentences:[{startsAtMs:0,endsAtMs:250},{startsAtMs:250,endsAtMs:500}]};assert.throws(()=>buildVideoTimeline(shortRender,shortSpeech,500),/too short/u);});

const box=(type:string,payload=Buffer.alloc(0))=>{const value=Buffer.alloc(8+payload.length);value.writeUInt32BE(value.length,0);value.write(type,4,"ascii");payload.copy(value,8);return value;};
const mp4=()=>Buffer.concat([box("ftyp",Buffer.from("isom0000")),box("moov"),box("mdat",Buffer.from([0]))]);
const probe={durationMs:2500,frameCount:75,video:{codec:"h264",width:1920,height:1080,fps:30,pixelFormat:"yuv420p"},audio:{codec:"aac",sampleRateHz:48000,channels:2}};
test("validates ISO BMFF structure and trusted H264/AAC delivery metadata",()=>{assert.doesNotThrow(()=>validateMp4Artifact(mp4(),probe,75));assert.throws(()=>validateMp4Artifact(Buffer.concat([box("ftyp"),box("free"),box("mdat")]),probe,75),/required ISO/u);const corrupt=mp4();corrupt.writeUInt32BE(0xffff,0);assert.throws(()=>validateMp4Artifact(corrupt,probe,75),/invalid ISO/u);assert.throws(()=>validateMp4Artifact(mp4(),{...probe,video:{...probe.video,pixelFormat:"yuv444p"}},75),/delivery profile/u);assert.throws(()=>validateMp4Artifact(mp4(),{...probe,frameCount:74},75),/frame count/u);assert.throws(()=>validateMp4Artifact(mp4(),{...probe,durationMs:2700},75),/duration/u);});
