import assert from "node:assert/strict";
import test from "node:test";
import { parseRenderRequest, parseS3ArtifactRef } from "./protocol.js";

const hash = "a".repeat(64); const ref = `s3://courseforge-artifacts/artifacts/artifact-${hash}`;
const request = () => ({ schemaVersion: "2", engine: "playwright-ffmpeg", engineRevision: "renderer-1", deckArtifactRef: ref, audioArtifactRefs: [ref], quality: "final", inlineManifest: { schemaVersion: "2", revealContentHash: hash, renderManifest: { schemaVersion: "1", renderId: "render-1", deckId: "deck-1", deckRevision: "1", deckUri: "/artifact", width: 1920, height: 1080, fps: 30, output: { container: "mp4", videoCodec: "h264", pixelFormat: "yuv420p", audioCodec: "aac" }, segments: [{ slideId: "slide-one", order: 0, durationMs: 1000, transition: "fade", sourceHash: hash }] }, speechManifest: { totalMeasuredDurationMs: 1000, slides: [{ slideId: "slide-one", order: 0, measuredDurationMs: 1000, audioContentHash: hash }] }, imageAssets: [{ assetId: "11111111-1111-4111-8111-111111111111", artifactRef: ref, contentPath: "/v1/projects/22222222-2222-4222-8222-222222222222/image-assets/11111111-1111-4111-8111-111111111111/content", contentHash: hash, mediaType: "image/png", width: 100, height: 50 }], transitionPolicy:{schemaVersion:"1",policyVersion:"xfade-v1",durationMs:300} } });

test("accepts the exact versioned S3 staging contract", () => { const parsed = parseRenderRequest(request(), "renderer-1"); assert.equal(parsed.inlineManifest.renderManifest.segments[0]?.durationMs, 1000); assert.deepEqual(parseS3ArtifactRef(ref, "courseforge-artifacts"), { bucket: "courseforge-artifacts", key: `artifacts/artifact-${hash}` }); });
test("rejects artifact refs the worker cannot independently resolve", () => { assert.throws(() => parseRenderRequest({ ...request(), deckArtifactRef: `artifact://sha256/${hash}` }, "renderer-1"), /invalid_request/); });
test("rejects revision drift and duration disagreement", () => { assert.throws(() => parseRenderRequest(request(), "renderer-2"), /invalid_request/); const value = request(); value.inlineManifest.speechManifest.slides[0]!.measuredDurationMs = 999; assert.throws(() => parseRenderRequest(value, "renderer-1"), /timeline_mismatch/); });
test("rejects unexpected fields and traversal-like keys", () => { assert.throws(() => parseRenderRequest({ ...request(), unexpected: true }, "renderer-1"), /invalid_request/); assert.throws(() => parseS3ArtifactRef("s3://courseforge-artifacts/artifacts/../secret", "courseforge-artifacts"), /unsupported_artifact_ref/); });
test("rejects duplicate image ids and non-S3 image references", () => { const value = request(); value.inlineManifest.imageAssets.push({ ...value.inlineManifest.imageAssets[0]! }); assert.throws(() => parseRenderRequest(value, "renderer-1"), /invalid_request/); const other = request(); other.inlineManifest.imageAssets[0]!.artifactRef = `https://evil.invalid/${hash}`; assert.throws(() => parseRenderRequest(other, "renderer-1"), /invalid_request/); });
test("rejects protocol v1 and unbounded transition policy",()=>{assert.throws(()=>parseRenderRequest({...request(),schemaVersion:"1"},"renderer-1"),/invalid_request/u);const value=request();value.inlineManifest.transitionPolicy.durationMs=501;assert.throws(()=>parseRenderRequest(value,"renderer-1"),/invalid_request/u);});
