import assert from "node:assert/strict";
import test from "node:test";
import sharp from "sharp";
import { CONTRACT_VERSION, type ProviderConfigVersionV1 } from "@courseforge/contracts";
import { InMemoryArtifactBlobStore } from "./artifacts.js";
import { importImageCandidate, searchImageCandidates } from "./image-search.js";
import { listImageAssets } from "./image-assets.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";

const projectId="22222222-2222-4222-8222-222222222222";const actor={schemaVersion:CONTRACT_VERSION,userId:"11111111-1111-4111-8111-111111111111",email:"editor@example.test",displayName:"Editor",role:"course_editor" as const};
async function fixture(){const repository=new InMemoryCourseForgeRepository();const blobs=new InMemoryArtifactBlobStore();await repository.saveProject({schemaVersion:"1",projectId,ownerId:actor.userId,dataPolicy:{schemaVersion:"1",mode:"public-only",classification:"public"},brief:{schemaVersion:"1",title:"公开培训",idea:"公开资料",audience:"公众",durationMinutes:20,objectives:["学习"],background:"",locale:"zh-CN",sourceArtifactIds:[]},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const config:ProviderConfigVersionV1={schemaVersion:"1",configId:crypto.randomUUID(),kind:"search",providerId:"agent-reach",version:"v1",displayName:"Search",capabilities:[],settings:{enabled:true,executable:"/opt/courseforge/mcporter",allowedExecutables:["/opt/courseforge/mcporter"],timeoutMs:1000,maxResults:5},secretRefs:{exa:"env://EXA_KEY"},status:"published",createdAt:new Date().toISOString(),createdBy:actor.userId,publishedAt:new Date().toISOString(),inactiveAt:null};await repository.createProviderConfig(config);const snapshot=await repository.captureRuntimeConfigSnapshot(crypto.randomUUID(),new Date().toISOString(),actor.userId);const runner={run:async()=>({exitCode:0,stderr:"",stdout:JSON.stringify({results:[{title:"安全办公插图",url:"https://source.example.test/page",imageUrl:"https://cdn.example.test/image.png",snippet:"候选，不代表已授权"}]})})};const result=await searchImageCandidates(repository,blobs,projectId,actor,{snapshotId:snapshot.snapshotId,query:"信息安全培训插图"},{commandRunner:runner,allowedSearchExecutables:["/opt/courseforge/mcporter"]});return{repository,blobs,result};}
test("governed search stores unverified candidates and never auto-imports assets",async()=>{const f=await fixture();assert.equal(f.result.set.candidates[0]?.status,"candidate-unverified");assert.equal((await listImageAssets(f.repository,f.blobs,projectId)).length,0);assert.equal(f.result.artifact.kind,"image-search-candidates");});
test("manual import requires license fields and safely decodes a public image",async()=>{const f=await fixture();const png=await sharp({create:{width:3,height:2,channels:3,background:"white"}}).png().toBuffer();const candidate=f.result.set.candidates[0]!;const asset=await importImageCandidate(f.repository,f.blobs,projectId,actor,{candidateArtifactId:f.result.artifact.artifactId,candidateId:candidate.candidateId,imageUrl:candidate.previewImageUrl!,author:"Example Author",licenseStatus:"licensed",usage:"内部培训视频与PPT",displayName:"安全插图"},{resolve:async()=>["93.184.216.34"],fetch:async()=>new Response(Uint8Array.from(png),{headers:{"content-type":"image/png","content-length":String(png.length)}})});assert.equal(asset.source.kind,"search-import");assert.equal(asset.source.sourceUrl,candidate.sourcePageUrl);assert.equal(asset.licensing.usage,"内部培训视频与PPT");});
test("SSRF, redirect rebinding, oversized bodies and MIME drift fail closed",async()=>{const f=await fixture();const candidate=f.result.set.candidates[0]!;const input={candidateArtifactId:f.result.artifact.artifactId,candidateId:candidate.candidateId,imageUrl:candidate.previewImageUrl!,author:"Author",licenseStatus:"cc0" as const,usage:"内部培训",displayName:"图"};await assert.rejects(importImageCandidate(f.repository,f.blobs,projectId,actor,{...input,imageUrl:"https://other.example.test/unrelated.png"},{resolve:async()=>["93.184.216.34"]}),/candidate_image_url_mismatch/);await assert.rejects(importImageCandidate(f.repository,f.blobs,projectId,actor,input,{resolve:async()=>["127.0.0.1"]}),/unsafe_image_url/);let calls=0;await assert.rejects(importImageCandidate(f.repository,f.blobs,projectId,actor,input,{resolve:async(host)=>host==="private.example.test"?["10.0.0.1"]:["93.184.216.34"],fetch:async()=>{calls++;return new Response(null,{status:302,headers:{location:"https://private.example.test/x.png"}})}}),/unsafe_image_url/);assert.equal(calls,1);const png=await sharp({create:{width:1,height:1,channels:3,background:"white"}}).png().toBuffer();let resolutions=0;await importImageCandidate(f.repository,f.blobs,projectId,actor,input,{resolve:async()=>{resolutions++;return["93.184.216.34"];},pinnedTransport:async(_url,addresses)=>{assert.deepEqual(addresses,["93.184.216.34"]);return new Response(Uint8Array.from(png),{headers:{"content-type":"image/png"}});}});assert.equal(resolutions,1);await assert.rejects(importImageCandidate(f.repository,f.blobs,projectId,actor,input,{resolve:async()=>["93.184.216.34"],fetch:async()=>new Response(new Uint8Array(10*1024*1024+1),{headers:{"content-type":"image/png"}})}),/image_too_large/);await assert.rejects(importImageCandidate(f.repository,f.blobs,projectId,actor,input,{resolve:async()=>["93.184.216.34"],fetch:async()=>new Response("html",{headers:{"content-type":"text/html"}})}),/invalid_image_response/);});
