import { createHash } from "node:crypto";
import { isIP } from "node:net";
import { lookup } from "node:dns/promises";
import { request as httpsRequest } from "node:https";
import { AgentReachSearchProvider, type CommandRunner, type FetchPort, type SecretResolver } from "@courseforge/providers";
import { ImageSearchCandidateSetV1Schema, type ImageAssetV1, type SessionUserV1 } from "@courseforge/contracts";
import { persistBinaryArtifact, type ArtifactBlobStore } from "./artifacts.js";
import { EnvironmentSecretResolver, SpawnCommandRunner, type PersistedProviderRuntimeOptions } from "./provider-runtime.js";
import { MAX_IMAGE_BYTES, persistImageAsset } from "./image-assets.js";
import type { CourseForgeRepository } from "./repositories.js";
import { enforceProjectDataPolicy } from "./project-data-policy.js";

const hash=(bytes:Uint8Array)=>createHash("sha256").update(bytes).digest("hex");
const stringSetting=(settings:Record<string,unknown>,key:string)=>{const value=settings[key];if(typeof value!=="string"||!value.trim())throw new Error("search_configuration_invalid");return value.trim();};
const numberSetting=(settings:Record<string,unknown>,key:string,fallback:number)=>{const value=settings[key]??fallback;if(typeof value!=="number"||!Number.isInteger(value))throw new Error("search_configuration_invalid");return value;};

export async function searchImageCandidates(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,actor:SessionUserV1,input:{snapshotId:string;query:string;limit?:number},options:PersistedProviderRuntimeOptions={}){
  const snapshot=await repository.findRuntimeConfigSnapshot(input.snapshotId);const binding=snapshot?.providerBindings.find((item)=>item.kind==="search");if(!snapshot||!binding)throw new Error("search_disabled");const config=await repository.findProviderConfig(binding.configId);
  if(!config||config.status!=="published"||config.kind!=="search"||config.providerId!==binding.providerId||config.version!==binding.version||config.settings.enabled!==true)throw new Error("search_disabled");
  const project=await repository.findProject(projectId);if(!project)throw new Error("project_unavailable");enforceProjectDataPolicy(project,config,"public-query");
  const executable=stringSetting(config.settings,"executable");const deploymentAllowed=options.allowedSearchExecutables??["/workspace/node_modules/.bin/mcporter"];const captured=config.settings.allowedExecutables;if(!Array.isArray(captured)||captured.some((item)=>typeof item!=="string")||!deploymentAllowed.includes(executable)||!captured.includes(executable))throw new Error("search_configuration_invalid");
  let runner:CommandRunner;if(options.commandRunner)runner=options.commandRunner;else{const reference=config.secretRefs.exa??Object.values(config.secretRefs)[0];if(!reference)throw new Error("search_configuration_invalid");const secret=await(options.secrets??new EnvironmentSecretResolver()).resolve(reference);if(!secret)throw new Error("search_configuration_invalid");runner=new SpawnCommandRunner({...process.env,EXA_API_KEY:secret});}
  const provider=new AgentReachSearchProvider({id:config.providerId,executable,allowedExecutables:captured as string[],timeoutMs:numberSetting(config.settings,"timeoutMs",30_000),maxResults:numberSetting(config.settings,"maxResults",20),maxOutputBytes:numberSetting(config.settings,"maxOutputBytes",2*1024*1024)},runner);
  const results=await provider.search({query:input.query,limit:input.limit??12},{runId:crypto.randomUUID(),projectId,configurationVersion:input.snapshotId});const createdAt=new Date().toISOString();
  const candidates=results.filter((item)=>new URL(item.url).protocol==="https:").map((item)=>({schemaVersion:"1" as const,candidateId:crypto.randomUUID(),projectId,snapshotId:input.snapshotId,query:input.query,title:item.title.slice(0,1000),sourcePageUrl:item.url,...(item.imageUrl?{previewImageUrl:item.imageUrl}:{}),snippet:item.snippet.slice(0,5000),providerId:config.providerId,status:"candidate-unverified" as const,discoveredAt:createdAt}));
  const set=ImageSearchCandidateSetV1Schema.parse({schemaVersion:"1",searchId:crypto.randomUUID(),projectId,snapshotId:input.snapshotId,query:input.query,candidates,createdAt,createdBy:actor.userId});const artifact=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:input.snapshotId,providerId:config.providerId,kind:"image-search-candidates",mediaType:"application/json",content:Buffer.from(JSON.stringify(set))});return{set,artifact};
}

function publicAddress(address:string){if(isIP(address)===4){const p=address.split(".").map(Number);return !(p[0]===0||p[0]===10||p[0]===127||p[0]!>=224||p[0]===169&&p[1]===254||p[0]===172&&p[1]!>=16&&p[1]!<=31||p[0]===192&&p[1]===168||p[0]===100&&p[1]!>=64&&p[1]!<=127);}const x=address.toLowerCase();return isIP(address)===6&&!(/^::$|^::1$|^f[cd]|^fe[89ab]|^::ffff:/u.test(x));}
export interface ImageImportOptions{fetch?:FetchPort;resolve?: (hostname:string)=>Promise<readonly string[]>;pinnedTransport?: (url:URL,addresses:readonly string[],signal:AbortSignal)=>Promise<Response>}
async function safeUrl(raw:string,resolve:(hostname:string)=>Promise<readonly string[]>){const url=new URL(raw);if(url.protocol!=="https:"||url.username||url.password||url.hash||url.port)throw new Error("unsafe_image_url");const addresses=await resolve(url.hostname);if(addresses.length<1||addresses.some((address)=>!publicAddress(address)))throw new Error("unsafe_image_url");return{url,addresses};}
async function pinnedFetch(url:URL,addresses:readonly string[],signal:AbortSignal):Promise<Response>{const address=addresses[0]!;return await new Promise<Response>((resolve,reject)=>{const req=httpsRequest({protocol:"https:",hostname:url.hostname,servername:url.hostname,path:`${url.pathname}${url.search}`,method:"GET",headers:{host:url.hostname,accept:"image/png,image/jpeg,image/webp"},signal,lookup:((_hostname:string,_options:unknown,callback:(error:Error|null,address:string,family:number)=>void)=>callback(null,address,isIP(address))) as never},(incoming)=>{const body=new ReadableStream<Uint8Array>({start(controller){incoming.on("data",(chunk:Buffer)=>controller.enqueue(Uint8Array.from(chunk)));incoming.on("end",()=>controller.close());incoming.on("error",(error)=>controller.error(error));}});resolve(new Response(body,{status:incoming.statusCode??500,headers:incoming.headers as HeadersInit}));});req.once("error",reject);req.end();});}
async function bounded(response:Response){if(!response.body)throw new Error("invalid_image_response");const chunks:Uint8Array[]=[];let total=0;const reader=response.body.getReader();try{while(true){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX_IMAGE_BYTES){await reader.cancel();throw new Error("image_too_large");}chunks.push(part.value);}}finally{reader.releaseLock();}return Uint8Array.from(Buffer.concat(chunks.map((item)=>Buffer.from(item)),total));}
export async function importImageCandidate(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,actor:SessionUserV1,input:{candidateArtifactId:string;candidateId:string;imageUrl:string;author:string;licenseStatus:"company-owned"|"licensed"|"cc0";usage:string;displayName:string},options:ImageImportOptions={}){
  const metadata=await repository.findArtifactMetadata(input.candidateArtifactId);if(!metadata||metadata.projectId!==projectId||metadata.kind!=="image-search-candidates")throw new Error("candidate_unavailable");const stored=await blobs.get(metadata.artifactId);if(!stored||stored.byteLength!==metadata.byteLength||hash(stored)!==metadata.contentHash)throw new Error("candidate_unavailable");const set=ImageSearchCandidateSetV1Schema.parse(JSON.parse(Buffer.from(stored).toString("utf8")));const candidate=set.candidates.find((item)=>item.candidateId===input.candidateId);if(!candidate)throw new Error("candidate_unavailable");
  if(!candidate.previewImageUrl||new URL(input.imageUrl).toString()!==new URL(candidate.previewImageUrl).toString())throw new Error("candidate_image_url_mismatch");
  const resolve=options.resolve??(async(hostname)=>{const rows=await lookup(hostname,{all:true,verbatim:true});return rows.map((item)=>item.address);});let target=await safeUrl(input.imageUrl,resolve);let url=target.url;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20_000);let response:Response;
  try{for(let redirects=0;;redirects++){response=options.fetch?await options.fetch(url,{method:"GET",redirect:"manual",signal:controller.signal,headers:{accept:"image/png,image/jpeg,image/webp"}}):await(options.pinnedTransport??pinnedFetch)(url,target.addresses,controller.signal);if(response.status<300||response.status>=400)break;if(redirects>=2)throw new Error("image_redirect_limit");const location=response.headers.get("location");if(!location)throw new Error("invalid_image_redirect");target=await safeUrl(new URL(location,url).toString(),resolve);url=target.url;}}catch(error){clearTimeout(timer);if(error instanceof Error&&/^(?:unsafe_image_url|image_redirect_limit|invalid_image_redirect)$/u.test(error.message))throw error;throw new Error("image_fetch_failed");}
  try{if(!response!.ok)throw new Error("image_fetch_failed");const mediaType=(response!.headers.get("content-type")??"").split(";",1)[0]!.toLowerCase();if(!["image/png","image/jpeg","image/webp"].includes(mediaType))throw new Error("invalid_image_response");const declared=Number(response!.headers.get("content-length")??0);if(declared>MAX_IMAGE_BYTES)throw new Error("image_too_large");const bytes=await bounded(response!);return await persistImageAsset(repository,blobs,projectId,actor,bytes,mediaType,{displayName:input.displayName,originalFilename:new URL(url).pathname.split("/").pop()||"imported-image",licenseStatus:input.licenseStatus,attribution:input.author,usage:input.usage,sourceUrl:candidate.sourcePageUrl,sourceKind:"search-import"});}finally{clearTimeout(timer);}
}
