import assert from "node:assert/strict";
import test from "node:test";
import type { ProjectV1, ProviderConfigVersionV1 } from "@courseforge/contracts";
import { enforceProjectDataPolicy } from "./project-data-policy.js";

const baseProject:ProjectV1={schemaVersion:"1",projectId:"22222222-2222-4222-8222-222222222222",ownerId:"11111111-1111-4111-8111-111111111111",brief:{schemaVersion:"1",title:"T",idea:"I",audience:"A",durationMinutes:20,objectives:["O"],background:"",locale:"zh-CN",sourceArtifactIds:[]},createdAt:new Date(0).toISOString(),updatedAt:new Date(0).toISOString()};
const config=(kind:ProviderConfigVersionV1["kind"],settings:Record<string,unknown>={},endpoint?:string):ProviderConfigVersionV1=>({schemaVersion:"1",configId:crypto.randomUUID(),kind,providerId:"test",version:"v1",displayName:"Test",...(endpoint?{endpoint}:{}),capabilities:[],settings:settings as never,secretRefs:{},status:"published",createdAt:new Date(0).toISOString(),createdBy:baseProject.ownerId,publishedAt:new Date(0).toISOString(),inactiveAt:null});

test("offline default denies every external governed provider before execution",()=>{assert.throws(()=>enforceProjectDataPolicy(baseProject,config("text"),"internal-content"),/offline/);assert.throws(()=>enforceProjectDataPolicy(baseProject,config("search"),"public-query"),/offline/);});
test("internal requires exact marked origin or executable",()=>{const project={...baseProject,dataPolicy:{schemaVersion:"1" as const,mode:"internal" as const,classification:"internal" as const}};assert.throws(()=>enforceProjectDataPolicy(project,config("text",{},"https://model.example.test/v1"),"internal-content"),/not_marked/);assert.doesNotThrow(()=>enforceProjectDataPolicy(project,config("text",{dataBoundary:"internal",internalAllowedOrigins:["https://model.example.test"]},"https://model.example.test/v1"),"internal-content"));assert.throws(()=>enforceProjectDataPolicy(project,config("search",{dataBoundary:"internal",executable:"runner",internalAllowedExecutables:["other"]}),"public-query"),/executable_not_exact/);});
test("public-only permits structured public search queries but rejects internal content",()=>{const project={...baseProject,dataPolicy:{schemaVersion:"1" as const,mode:"public-only" as const,classification:"public" as const}};assert.doesNotThrow(()=>enforceProjectDataPolicy(project,config("search"),"public-query"));assert.throws(()=>enforceProjectDataPolicy(project,config("text"),"internal-content"),/content_forbidden/);});
