import assert from "node:assert/strict";
import test from "node:test";
import { BUSINESS_PROMPT_KEYS, PROMPT_DEFINITION_CATALOG, initializeMissingPrompts, promptCatalogStatus, promptContentHash, validatePromptTemplate } from "./prompt-catalog.js";
import { bootstrapMissingPromptDrafts, SYSTEM_ACTOR_ID } from "./bootstrap.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";

test("prompt catalog exposes ten editable business prompts and read-only safety definitions",async()=>{const repository=new InMemoryCourseForgeRepository();assert.equal(BUSINESS_PROMPT_KEYS.length,10);assert.equal(PROMPT_DEFINITION_CATALOG.filter(item=>item.editable).length,10);assert.equal(PROMPT_DEFINITION_CATALOG.filter(item=>!item.editable).length,4);const before=await promptCatalogStatus(repository);assert.equal(before.filter(item=>item.status==="missing").length,10);const actorId=crypto.randomUUID(),created=await initializeMissingPrompts(repository,actorId,"v1");assert.equal(created.length,10);assert.ok(created.every(item=>item.status==="draft"&&item.createdBy===actorId));assert.equal((await initializeMissingPrompts(repository,actorId,"v1")).length,0);assert.equal((await promptCatalogStatus(repository)).filter(item=>item.status==="missing").length,10);});

test("startup bootstrap creates drafts for missing business prompts, is idempotent and never overwrites existing versions",async()=>{const repository=new InMemoryCourseForgeRepository();const created=await bootstrapMissingPromptDrafts(repository,SYSTEM_ACTOR_ID,"v1");assert.equal(created.length,10);assert.ok(created.every(item=>item.status==="draft"&&item.createdBy===SYSTEM_ACTOR_ID&&BUSINESS_PROMPT_KEYS.includes(item.promptKey as typeof BUSINESS_PROMPT_KEYS[number])));assert.equal((await bootstrapMissingPromptDrafts(repository,SYSTEM_ACTOR_ID,"v1")).length,0,"second run must create nothing");const all=await repository.listPromptVersions();assert.equal(all.length,10);await repository.publishPromptVersion(all[0]!.promptVersionId,new Date().toISOString());assert.equal((await bootstrapMissingPromptDrafts(repository,SYSTEM_ACTOR_ID,"v1")).length,0,"existing versions, including drafts, block re-creation");});

test("prompt variable validation rejects undeclared placeholders and hashes exact immutable content",()=>{const definition=PROMPT_DEFINITION_CATALOG.find(item=>item.promptKey==="course.research")!;assert.doesNotThrow(()=>validatePromptTemplate(definition,definition.defaultTemplate));assert.throws(()=>validatePromptTemplate(definition,"{{credential}}"),/prompt_variable_not_allowed/u);const prompt={promptKey:"course.research",version:"v1",template:"safe"};assert.equal(promptContentHash(prompt),promptContentHash({...prompt}));assert.notEqual(promptContentHash(prompt),promptContentHash({...prompt,template:"changed"}));});
