import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { CONTRACT_VERSION, QaReportV1Schema } from "@courseforge/contracts";
import { buildImportedSource } from "./source-revisions.js";
import { InMemoryArtifactBlobStore, persistBinaryArtifact, persistContentJsonArtifact } from "./artifacts.js";
import { isFinalVideoEvidence, recordQaApproval, speakerNarrationSynchronized, verifiedResearchEvidenceSourceIds, verifiedUploadedSourceIds } from "./qa-publication.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";

const projectId="22222222-2222-4222-8222-222222222222"; const actor={schemaVersion:CONTRACT_VERSION,userId:"11111111-1111-4111-8111-111111111111",email:"editor@example.test",displayName:"Editor",role:"course_editor" as const};
test("human approval requires an existing same-project evidence artifact with exact hash", async()=>{const repository=new InMemoryCourseForgeRepository();const blobs=new InMemoryArtifactBlobStore();const ids=["a","b","c"].map((x)=>`artifact-${x.repeat(64)}`);const report=QaReportV1Schema.parse({schemaVersion:"1",qaReportId:crypto.randomUUID(),projectId,deckArtifactId:ids[0],speechManifestArtifactId:ids[1],videoManifestArtifactId:ids[2],configurationSnapshotId:crypto.randomUUID(),qaPolicy:{qaPolicyId:crypto.randomUUID(),version:"v1",contentHash:"d".repeat(64)},checks:[{checkId:"ok",status:"passed",message:"ok",artifactIds:[]}],blockerCount:0,warningCount:0,createdAt:new Date().toISOString(),createdBy:actor.userId});const reportArtifact=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:report.configurationSnapshotId,providerId:"qa",kind:"qa-report",mediaType:"application/json",content:Buffer.from(JSON.stringify(report))});const evidence=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:"evidence-v1",providerId:"evidence",kind:"visual-analysis",mediaType:"application/json",content:Buffer.from("{}")});await assert.rejects(recordQaApproval(repository,blobs,projectId,actor,{qaReportArtifactId:reportArtifact.artifactId,type:"copyright-review",evidenceArtifactId:evidence.artifactId,evidenceSha256:"f".repeat(64),note:"已人工核对"}),/invalid_approval_evidence/);const result=await recordQaApproval(repository,blobs,projectId,actor,{qaReportArtifactId:reportArtifact.artifactId,type:"copyright-review",evidenceArtifactId:evidence.artifactId,evidenceSha256:evidence.contentHash,note:"已人工核对"});assert.equal(result.approval.evidenceArtifactId,evidence.artifactId);});
test("Draft video is preview-only and cannot satisfy publication evidence",()=>{assert.equal(isFinalVideoEvidence({renderMode:"final-static-xfade-v1",evidenceClass:"preview-only"}),false);assert.equal(isFinalVideoEvidence({renderMode:"final-static-xfade-v1",evidenceClass:"deterministic-final"}),true);});
test("QA requires Reveal speaker notes to match the narration actually synthesized",()=>{const notes="最终讲稿。",hash=createHash("sha256").update(notes).digest("hex");assert.equal(speakerNarrationSynchronized({slides:[{slideId:"slide-one",speakerNotes:notes}]},{slides:[{slideId:"slide-one",narrationSha256:hash}]}),true);assert.equal(speakerNarrationSynchronized({slides:[{slideId:"slide-one",speakerNotes:"旧讲稿。"}]},{slides:[{slideId:"slide-one",narrationSha256:hash}]}),false);});
test("QA accepts only same-project hash-verified research evidence sources",async()=>{const repository=new InMemoryCourseForgeRepository(),blobs=new InMemoryArtifactBlobStore();const text="官方证据";const hash=createHash("sha256").update(text).digest("hex"),sourceId=`evidence-${hash.slice(0,32)}`;const evidence=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:"snapshot",providerId:"secure-evidence-fetch-v1",kind:"research-evidence",mediaType:"application/json",content:Buffer.from(JSON.stringify({schemaVersion:"1",sourceId,urlHash:"a".repeat(64),host:"example.test",retrievedAt:new Date(0).toISOString(),contentHash:hash,mediaType:"text/plain",text,locator:{kind:"text-quote",quote:text,start:0,end:text.length}}))});await persistContentJsonArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:"snapshot",providerId:"pipeline",kind:"research-json",value:{schemaVersion:"1",queries:["q"],sources:[{sourceId,title:"指南",snippet:text,sourceKind:"web",evidenceContentHash:hash,urlHash:"a".repeat(64),host:"example.test",retrievedAt:new Date(0).toISOString(),locator:{kind:"text-quote",quote:text,start:0,end:text.length}}]},sourceArtifactIds:[evidence.artifactId]});assert.equal((await verifiedResearchEvidenceSourceIds(repository,blobs,projectId)).has(sourceId),true);const bytes=await blobs.get(evidence.artifactId);await blobs.put(evidence.artifactId,Buffer.concat([Buffer.from(bytes!),Buffer.from("x")]));await assert.rejects(verifiedResearchEvidenceSourceIds(repository,blobs,projectId),/integrity/)});
test("QA accepts both artifact and revision identities for verified project uploads",async()=>{const repository=new InMemoryCourseForgeRepository();const imported=buildImportedSource(projectId,"policy.md","text/markdown",Buffer.from("# 制度\n\n发现风险立即上报。"));await repository.saveImportedSource(imported);const ids=await verifiedUploadedSourceIds(repository,projectId);assert.equal(ids.has(imported.artifact.sourceArtifactId),true);assert.equal(ids.has(imported.revision.sourceRevisionId),true);assert.equal((await verifiedUploadedSourceIds(repository,crypto.randomUUID())).size,0);});
