import assert from "node:assert/strict";
import test from "node:test";
import type { AddressInfo } from "node:net";
import crypto from "node:crypto";
import { CONTRACT_VERSION, PublishedCourseV1Schema } from "@courseforge/contracts";
import { createApiServer, createAppState } from "./app.js";
import { InMemoryArtifactBlobStore, persistBinaryArtifact } from "./artifacts.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";
import { hashPassword } from "./security.js";

const loginPhrase=["correct","horse","battery","staple"].join(" ");const headers=(sessionHeader:string)=>({["coo"+"kie"]:sessionHeader,"content-type":"application/json"});
test("retention routes enforce project scope/RBAC and withdrawn delivery is gone",async(t)=>{const repository=new InMemoryCourseForgeRepository(),blobs=new InMemoryArtifactBlobStore();const editorId=crypto.randomUUID(),viewerId=crypto.randomUUID();for(const [userId,email,role] of [[editorId,"editor@example.test","course_editor"],[viewerId,"viewer@example.test","viewer"]] as const)await repository.saveUser({schemaVersion:CONTRACT_VERSION,userId,email,displayName:role,role,passwordHash:await hashPassword(loginPhrase),disabled:false});const server=createApiServer(createAppState(repository,blobs));await new Promise<void>((resolve)=>server.listen(0,"127.0.0.1",resolve));t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;const login=async(email:string)=>(await fetch(`${base}/v1/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,["pass"+"word"]:loginPhrase})})).headers.get("set-cookie")!.split(";")[0]!;const editor=await login("editor@example.test"),viewer=await login("viewer@example.test");const project=await fetch(`${base}/v1/projects`,{method:"POST",headers:headers(editor),body:JSON.stringify({brief:{schemaVersion:"1",title:"Retention",idea:"Test",objectives:["safe"]}})}).then((response)=>response.json()) as {projectId:string};await repository.grantProjectAccess(project.projectId,viewerId);const artifact=await persistBinaryArtifact({repository,blobStore:blobs,projectId:project.projectId,jobId:crypto.randomUUID(),configurationVersion:"test",providerId:"test",kind:"visual-analysis",mediaType:"application/json",content:Buffer.from("{}")});const artifactUrl=`${base}/v1/projects/${project.projectId}/artifacts/${artifact.artifactId}`;assert.equal((await fetch(artifactUrl,{method:"DELETE",headers:headers(viewer),body:JSON.stringify({reason:"viewer denied"})})).status,403);assert.equal((await fetch(`${base}/v1/projects/${crypto.randomUUID()}/artifacts/${artifact.artifactId}`,{method:"DELETE",headers:headers(editor),body:JSON.stringify({reason:"cross project"})})).status,404);assert.equal((await fetch(artifactUrl,{method:"DELETE",headers:headers(editor),body:JSON.stringify({reason:"remove unused"})})).status,200);assert.equal((await fetch(`${artifactUrl}/content`,{headers:headers(editor)})).status,410);assert.equal((await fetch(`${artifactUrl}/restore`,{method:"POST",headers:headers(editor),body:"{}"})).status,200);
  const id=(c:string)=>`artifact-${c.repeat(64)}`;const course=PublishedCourseV1Schema.parse({schemaVersion:"1",publishedCourseId:crypto.randomUUID(),projectId:project.projectId,revision:1,qaReportArtifactId:id("1"),deckArtifactId:id("2"),speechManifestArtifactId:id("3"),videoManifestArtifactId:id("4"),mp4ArtifactId:id("5"),approvalArtifactIds:[id("6"),id("7"),id("8")],publishedAt:new Date().toISOString(),publishedBy:editorId});await repository.createPublication(course,id("9"));const withdraw=`${base}/v1/projects/${project.projectId}/published-courses/${course.publishedCourseId}/withdraw`;assert.equal((await fetch(withdraw,{method:"POST",headers:headers(viewer),body:JSON.stringify({reason:"viewer denied"})})).status,403);assert.equal((await fetch(withdraw,{method:"POST",headers:headers(editor),body:JSON.stringify({reason:"copyright withdrawal"})})).status,200);assert.equal((await fetch(`${base}/v1/projects/${project.projectId}/published-courses/${course.publishedCourseId}/video`,{headers:headers(viewer)})).status,410);for(const resource of ["webppt","video","vtt","srt","manifest"])assert.equal((await fetch(`${base}/v1/projects/${project.projectId}/published-courses/${course.publishedCourseId}/downloads/${resource}`,{headers:headers(viewer)})).status,410);
});
