import assert from "node:assert/strict";
import test from "node:test";
import crypto from "node:crypto";
import { ArtifactTombstoneV1Schema, PublishedCourseV1Schema, type SessionUserV1 } from "@courseforge/contracts";
import { InMemoryArtifactBlobStore, persistBinaryArtifact } from "./artifacts.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";
import { InMemoryArtifactGarbageCollector, createGcPlan, executeGcPlan, listPublicationRecords, restoreArtifact, tombstoneArtifact, withdrawPublication } from "./retention.js";

const projectId="11111111-1111-4111-8111-111111111111",otherProjectId="22222222-2222-4222-8222-222222222222";
const actor:SessionUserV1={schemaVersion:"1",userId:"33333333-3333-4333-8333-333333333333",email:"editor@example.test",displayName:"Editor",role:"course_editor"};
const save=async(repository:InMemoryCourseForgeRepository,blobs:InMemoryArtifactBlobStore,project=projectId,sourceArtifactIds:string[]=[])=>persistBinaryArtifact({repository,blobStore:blobs,projectId:project,jobId:crypto.randomUUID(),configurationVersion:"test",providerId:"test",kind:"visual-analysis",mediaType:"application/json",content:Buffer.from(JSON.stringify({nonce:crypto.randomUUID()})),sourceArtifactIds});

test("tombstones are scoped, idempotent, reference-safe and recoverable",async()=>{const repository=new InMemoryCourseForgeRepository(),blobs=new InMemoryArtifactBlobStore();const target=await save(repository,blobs);await assert.rejects(tombstoneArtifact(repository,blobs,otherProjectId,actor,target.artifactId,"remove unused"),/artifact_not_found/);const dependent=await save(repository,blobs,projectId,[target.artifactId]);await assert.rejects(tombstoneArtifact(repository,blobs,projectId,actor,target.artifactId,"remove unused"),/artifact_referenced/);const value=await tombstoneArtifact(repository,blobs,projectId,actor,dependent.artifactId,"remove unused");assert.equal((await tombstoneArtifact(repository,blobs,projectId,actor,dependent.artifactId,"remove unused")).tombstoneId,value.tombstoneId);const restored=await restoreArtifact(repository,projectId,actor,dependent.artifactId);assert.equal(restored.restoredBy,actor.userId);await assert.rejects(restoreArtifact(repository,projectId,actor,dependent.artifactId),/tombstone_not_found/);});

test("withdrawal is immutable and does not rewrite published course",async()=>{const repository=new InMemoryCourseForgeRepository();const id=(c:string)=>`artifact-${c.repeat(64)}`;const course=PublishedCourseV1Schema.parse({schemaVersion:"1",publishedCourseId:crypto.randomUUID(),projectId,revision:1,qaReportArtifactId:id("1"),deckArtifactId:id("2"),speechManifestArtifactId:id("3"),videoManifestArtifactId:id("4"),mp4ArtifactId:id("5"),approvalArtifactIds:[id("6"),id("7"),id("8")],publishedAt:new Date().toISOString(),publishedBy:actor.userId});await repository.createPublication(course,id("9"));const first=await withdrawPublication(repository,projectId,actor,course.publishedCourseId,"copyright owner requested withdrawal");const second=await withdrawPublication(repository,projectId,actor,course.publishedCourseId,"different reason is ignored");assert.equal(second.withdrawalId,first.withdrawalId);const records=await listPublicationRecords(repository,projectId);assert.equal(records[0]?.status,"withdrawn");assert.deepEqual(records[0]?.course,course);await assert.rejects(withdrawPublication(repository,otherProjectId,actor,course.publishedCourseId,"cross project"),/publication_not_found/);});

test("GC requires elapsed retention, exact confirmation and rechecks references",async()=>{const repository=new InMemoryCourseForgeRepository(),blobs=new InMemoryArtifactBlobStore(),gc=new InMemoryArtifactGarbageCollector();const artifact=await save(repository,blobs);const yesterday=new Date(Date.now()-86_400_000).toISOString();const old=ArtifactTombstoneV1Schema.parse({schemaVersion:"1",tombstoneId:crypto.randomUUID(),artifactId:artifact.artifactId,projectId,reason:"expired retention",tombstonedAt:new Date(Date.now()-40*86_400_000).toISOString(),tombstonedBy:actor.userId,restoreDeadline:yesterday,restoredAt:null,restoredBy:null,purgedAt:null,purgedBy:null});await repository.saveArtifactTombstone(old);await assert.rejects(restoreArtifact(repository,projectId,actor,artifact.artifactId),/restore_window_expired/);const plan=await createGcPlan(repository,blobs,{...actor,role:"platform_admin"});await assert.rejects(executeGcPlan(repository,blobs,gc,{...actor,role:"platform_admin"},plan.planId,"f".repeat(64)),/gc_plan_invalid/);const executed=await executeGcPlan(repository,blobs,gc,{...actor,role:"platform_admin"},plan.planId,plan.confirmationSha256);assert.equal(executed.executedBy,actor.userId);assert.deepEqual(gc.deleted,[artifact.artifactId]);await assert.rejects(executeGcPlan(repository,blobs,gc,{...actor,role:"platform_admin"},plan.planId,plan.confirmationSha256),/gc_plan_invalid/);});
