import assert from "node:assert/strict"; import test from "node:test";
import { InMemoryArtifactStore, createDeckArtifactBuilder } from "@courseforge/deck";
import { persistDeckArtifactBundle, InMemoryArtifactBlobStore } from "./artifacts.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";
import { InMemoryRevisionRepository } from "./revision-repository.js";
import { RevisionService } from "./revision-service.js";

const actor={schemaVersion:"1" as const,userId:crypto.randomUUID(),email:"editor@example.test",displayName:"Editor",role:"course_editor" as const};
const deck={schemaVersion:"1" as const,deckId:crypto.randomUUID(),revision:1,title:"Security",themeId:"dark",aspectRatio:"16:9" as const,slides:[{schemaVersion:"1" as const,slideId:"slide-one",title:"One",layout:"content" as const,blocks:[{kind:"text" as const,body:"Body"}],speakerNotes:"Notes",targetDurationSeconds:20,learningObjectiveIds:[],sourceIds:[],transition:"fade" as const},{schemaVersion:"1" as const,slideId:"slide-two",title:"Two",layout:"summary" as const,blocks:[],speakerNotes:"End",targetDurationSeconds:10,learningObjectiveIds:[],sourceIds:[],transition:"fade" as const}]};
async function fixture(){const repository=new InMemoryCourseForgeRepository();const blobs=new InMemoryArtifactBlobStore();const revisions=new InMemoryRevisionRepository();const projectId=crypto.randomUUID();const store=new InMemoryArtifactStore();const bundle=await createDeckArtifactBuilder(store)(deck,{projectId,jobId:crypto.randomUUID(),revision:1,configurationVersion:"test",providerId:"test"});await persistDeckArtifactBundle(repository,blobs,store,bundle);return{repository,blobs,revisions,projectId,service:new RevisionService(repository,blobs,revisions)};}

test("proposal requires explicit apply and marks media stale with cache evidence",async()=>{const f=await fixture();const active=await f.service.ensureActive(f.projectId,"deck",actor);const proposal=await f.service.createProposal(f.projectId,actor,{kind:"deck",baseRevisionId:active.revisionId,baseContentHash:active.contentHash,mode:"manual",patch:[{op:"replace",path:"/slides/0/speakerNotes",value:"Updated"}]});assert.equal((await f.revisions.findActive(f.projectId,"deck"))?.revision,1);const next=await f.service.apply(f.projectId,actor,proposal.proposalId);assert.equal(next.revision,2);assert.deepEqual(next.dirtySlideIds,["slide-one"]);assert.deepEqual(next.reusedSlideIds,["slide-two"]);assert.equal(next.mediaState,"stale_requires_regeneration");assert.ok((await f.repository.listArtifactMetadata(f.projectId)).filter(a=>a.kind==="deck-spec").length===2);});
test("stale base, locked paths, and cross-project revision reads fail closed",async()=>{const f=await fixture();const active=await f.service.ensureActive(f.projectId,"deck",actor);await assert.rejects(f.service.createProposal(f.projectId,actor,{kind:"deck",baseRevisionId:active.revisionId,baseContentHash:"0".repeat(64),mode:"manual",patch:[{op:"replace",path:"/title",value:"x"}]}),/stale/);assert.equal(await f.revisions.findRevision(crypto.randomUUID(),active.revisionId),undefined);});
test("material patches and restore create immutable revisions",async()=>{const repository=new InMemoryCourseForgeRepository();const blobs=new InMemoryArtifactBlobStore();const revisions=new InMemoryRevisionRepository();const projectId=crypto.randomUUID();const material={schemaVersion:"1",title:"Material",audience:"Staff",objective:"Learn",sections:[{title:"Policy",keyPoints:["One"],speakerNotes:"Talk",sourceIds:["source-one"]}]};const {persistContentJsonArtifact}=await import("./artifacts.js");await persistContentJsonArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:"test",providerId:"test",kind:"material-json",value:material});const service=new RevisionService(repository,blobs,revisions);const first=await service.ensureActive(projectId,"material",actor);const proposal=await service.createProposal(projectId,actor,{kind:"material",baseRevisionId:first.revisionId,baseContentHash:first.contentHash,mode:"manual",patch:[{op:"replace",path:"/sections/0/speakerNotes",value:"New talk"}]});const second=await service.apply(projectId,actor,proposal.proposalId);const restored=await service.restore(projectId,"material",actor,first.revisionId,second.revisionId,second.contentHash);assert.equal(restored.revision,3);assert.equal(restored.parentRevisionId,second.revisionId);assert.equal(restored.reason,"restore");assert.equal((restored.document as typeof material).sections[0]!.speakerNotes,"Talk");});
