import { RevisionProposalV1Schema, RevisionRecordV1Schema, type RevisionDocumentKind, type RevisionProposalV1, type RevisionRecordV1 } from "@courseforge/contracts";

export interface StoredRevision extends RevisionRecordV1 { document: unknown }
export interface RevisionRepository {
  findActive(projectId: string, kind: RevisionDocumentKind): Promise<StoredRevision | undefined>;
  findRevision(projectId: string, revisionId: string): Promise<StoredRevision | undefined>;
  listRevisions(projectId: string, kind: RevisionDocumentKind): Promise<RevisionRecordV1[]>;
  initialize(revision: StoredRevision): Promise<StoredRevision>;
  saveIfActive(revision: StoredRevision, expectedRevisionId: string, expectedHash: string): Promise<boolean>;
  saveProposal(proposal: RevisionProposalV1): Promise<void>;
  findProposal(projectId: string, proposalId: string): Promise<RevisionProposalV1 | undefined>;
  markProposalApplied(proposalId: string): Promise<void>;
}

const key = (projectId: string, kind: string) => `${projectId}:${kind}`;
export class InMemoryRevisionRepository implements RevisionRepository {
  private revisions = new Map<string, StoredRevision>(); private heads = new Map<string, string>(); private proposals = new Map<string, RevisionProposalV1>();
  async findActive(projectId: string, kind: RevisionDocumentKind) { const id = this.heads.get(key(projectId, kind)); const value = id ? this.revisions.get(id) : undefined; return value ? structuredClone(value) : undefined; }
  async findRevision(projectId: string, revisionId: string) { const value = this.revisions.get(revisionId); return value?.projectId === projectId ? structuredClone(value) : undefined; }
  async listRevisions(projectId: string, kind: RevisionDocumentKind) { return [...this.revisions.values()].filter((item) => item.projectId === projectId && item.kind === kind).sort((a,b) => b.revision-a.revision).map(({ document: _document, ...item }) => structuredClone(item)); }
  async initialize(revision: StoredRevision) { const existing = await this.findActive(revision.projectId, revision.kind); if (existing) return existing; this.revisions.set(revision.revisionId, structuredClone(revision)); this.heads.set(key(revision.projectId, revision.kind), revision.revisionId); return structuredClone(revision); }
  async saveIfActive(revision: StoredRevision, expectedRevisionId: string, expectedHash: string) { const active = await this.findActive(revision.projectId, revision.kind); if (!active || active.revisionId !== expectedRevisionId || active.contentHash !== expectedHash) return false; this.revisions.set(revision.revisionId, structuredClone(revision)); this.heads.set(key(revision.projectId, revision.kind), revision.revisionId); return true; }
  async saveProposal(proposal: RevisionProposalV1) { this.proposals.set(proposal.proposalId, structuredClone(RevisionProposalV1Schema.parse(proposal))); }
  async findProposal(projectId: string, proposalId: string) { const value = this.proposals.get(proposalId); return value?.projectId === projectId ? structuredClone(value) : undefined; }
  async markProposalApplied(proposalId: string) { const value = this.proposals.get(proposalId); if (value) this.proposals.set(proposalId, { ...value, status: "applied" }); }
}

interface SqlClient { query<Row>(text: string, values?: readonly unknown[]): Promise<{ rows: Row[]; rowCount?: number | null }> }
type RevisionRow = { document_record: unknown; document: unknown };
const parseStored = (row: RevisionRow): StoredRevision => ({ ...RevisionRecordV1Schema.parse(row.document_record), document: row.document });
export class PostgresRevisionRepository implements RevisionRepository {
  constructor(private client: SqlClient) {}
  async findActive(projectId: string, kind: RevisionDocumentKind) { const result = await this.client.query<RevisionRow>(`SELECT jsonb_build_object('schemaVersion','1','revisionId',r.revision_id,'projectId',r.project_id,'kind',r.kind,'revision',r.revision,'parentRevisionId',r.parent_revision_id,'artifactId',r.artifact_id,'contentHash',r.content_hash,'configurationSnapshotId',r.configuration_snapshot_id,'createdAt',r.created_at,'createdBy',r.created_by,'reason',r.reason,'locks',r.locks,'slideHashes',r.slide_hashes,'dirtySlideIds',r.dirty_slide_ids,'reusedSlideIds',r.reused_slide_ids,'mediaState',r.media_state) document_record, r.document FROM document_revision_heads h JOIN document_revisions r ON r.revision_id=h.revision_id WHERE h.project_id=$1 AND h.kind=$2`, [projectId, kind]); return result.rows[0] ? parseStored(result.rows[0]) : undefined; }
  async findRevision(projectId: string, revisionId: string) { const result = await this.client.query<RevisionRow>(`SELECT jsonb_build_object('schemaVersion','1','revisionId',revision_id,'projectId',project_id,'kind',kind,'revision',revision,'parentRevisionId',parent_revision_id,'artifactId',artifact_id,'contentHash',content_hash,'configurationSnapshotId',configuration_snapshot_id,'createdAt',created_at,'createdBy',created_by,'reason',reason,'locks',locks,'slideHashes',slide_hashes,'dirtySlideIds',dirty_slide_ids,'reusedSlideIds',reused_slide_ids,'mediaState',media_state) document_record, document FROM document_revisions WHERE project_id=$1 AND revision_id=$2`, [projectId, revisionId]); return result.rows[0] ? parseStored(result.rows[0]) : undefined; }
  async listRevisions(projectId: string, kind: RevisionDocumentKind) { const result = await this.client.query<RevisionRow>(`SELECT jsonb_build_object('schemaVersion','1','revisionId',revision_id,'projectId',project_id,'kind',kind,'revision',revision,'parentRevisionId',parent_revision_id,'artifactId',artifact_id,'contentHash',content_hash,'configurationSnapshotId',configuration_snapshot_id,'createdAt',created_at,'createdBy',created_by,'reason',reason,'locks',locks,'slideHashes',slide_hashes,'dirtySlideIds',dirty_slide_ids,'reusedSlideIds',reused_slide_ids,'mediaState',media_state) document_record, document FROM document_revisions WHERE project_id=$1 AND kind=$2 ORDER BY revision DESC`, [projectId, kind]); return result.rows.map((row) => RevisionRecordV1Schema.parse(row.document_record)); }
  private values(r: StoredRevision) { return [r.revisionId,r.projectId,r.kind,r.revision,r.parentRevisionId,r.artifactId,r.contentHash,r.configurationSnapshotId,JSON.stringify(r.document),JSON.stringify(r.locks),JSON.stringify(r.slideHashes),JSON.stringify(r.dirtySlideIds),JSON.stringify(r.reusedSlideIds),r.mediaState,r.reason,r.createdAt,r.createdBy]; }
  async initialize(r: StoredRevision) { await this.client.query(`WITH ins AS (INSERT INTO document_revisions(revision_id,project_id,kind,revision,parent_revision_id,artifact_id,content_hash,configuration_snapshot_id,document,locks,slide_hashes,dirty_slide_ids,reused_slide_ids,media_state,reason,created_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14,$15,$16,$17) ON CONFLICT(project_id,kind,revision) DO NOTHING RETURNING revision_id) INSERT INTO document_revision_heads(project_id,kind,revision_id) SELECT $2,$3,revision_id FROM ins ON CONFLICT(project_id,kind) DO NOTHING`, this.values(r)); return (await this.findActive(r.projectId,r.kind))!; }
  async saveIfActive(r: StoredRevision, expectedId: string, expectedHash: string) { const result = await this.client.query<{ revision_id: string }>(`WITH current AS (SELECT revision_id FROM document_revision_heads h JOIN document_revisions old ON old.revision_id=h.revision_id WHERE h.project_id=$2 AND h.kind=$3 AND h.revision_id=$18 AND old.content_hash=$19 FOR UPDATE), ins AS (INSERT INTO document_revisions(revision_id,project_id,kind,revision,parent_revision_id,artifact_id,content_hash,configuration_snapshot_id,document,locks,slide_hashes,dirty_slide_ids,reused_slide_ids,media_state,reason,created_at,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14,$15,$16,$17 FROM current RETURNING revision_id) UPDATE document_revision_heads SET revision_id=ins.revision_id FROM ins WHERE project_id=$2 AND kind=$3 RETURNING ins.revision_id`, [...this.values(r), expectedId, expectedHash]); return Boolean(result.rows[0]); }
  async saveProposal(p: RevisionProposalV1) { await this.client.query(`INSERT INTO document_revision_proposals(proposal_id,project_id,kind,base_revision_id,base_content_hash,mode,patch,changed_paths,configuration_snapshot_id,status,created_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9,$10,$11,$12)`, [p.proposalId,p.projectId,p.kind,p.baseRevisionId,p.baseContentHash,p.mode,JSON.stringify(p.patch),JSON.stringify(p.changedPaths),p.configurationSnapshotId,p.status,p.createdAt,p.createdBy]); }
  async findProposal(projectId: string, proposalId: string) { const result=await this.client.query<{ document: unknown }>(`SELECT jsonb_build_object('schemaVersion','1','proposalId',proposal_id,'projectId',project_id,'kind',kind,'baseRevisionId',base_revision_id,'baseContentHash',base_content_hash,'mode',mode,'patch',patch,'changedPaths',changed_paths,'configurationSnapshotId',configuration_snapshot_id,'createdAt',created_at,'createdBy',created_by,'status',status) document FROM document_revision_proposals WHERE project_id=$1 AND proposal_id=$2`,[projectId,proposalId]); return result.rows[0] ? RevisionProposalV1Schema.parse(result.rows[0].document) : undefined; }
  async markProposalApplied(proposalId: string) { await this.client.query("UPDATE document_revision_proposals SET status='applied' WHERE proposal_id=$1 AND status='pending'",[proposalId]); }
}
