import assert from "node:assert/strict";
import test from "node:test";
import { PromptVersionV1Schema, ProviderConfigVersionV1Schema } from "@courseforge/contracts";
import { InMemoryDesignTemplateStore } from "./design-templates.js";
import { InMemoryProviderGovernanceStore, safeProbeResult } from "./provider-governance.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";
import { evaluateRuntimeReadiness } from "./runtime-readiness.js";

test("runtime readiness reports concrete missing components and requires a probe newer than configuration",async()=>{const repository=new InMemoryCourseForgeRepository(),governance=new InMemoryProviderGovernanceStore(),designTemplates=new InMemoryDesignTemplateStore(),actor=crypto.randomUUID(),now=new Date().toISOString();const text=ProviderConfigVersionV1Schema.parse({schemaVersion:"1",configId:crypto.randomUUID(),kind:"text",providerId:"text",version:"v1",displayName:"Text",endpoint:"https://model.example/v1",model:"model",capabilities:["structured-output"],settings:{allowedOrigins:["https://model.example"]},secretRefs:{primary:"env://TEXT_KEY"},status:"published",createdAt:now,createdBy:actor,publishedAt:now,inactiveAt:null});await repository.createProviderConfig(text);const snapshot=await repository.captureRuntimeConfigSnapshot(crypto.randomUUID(),new Date().toISOString(),actor);const first=await evaluateRuntimeReadiness({repository,governance,designTemplates,snapshot});assert.equal(first.runnable,false);assert.ok(first.missing.some(item=>item.key==="text"&&item.code==="provider_probe_missing"));assert.ok(first.missing.some(item=>item.key==="course.deck"&&item.code==="prompt_binding_missing"));await governance.saveProbe(safeProbeResult(text,actor,{healthy:true,capabilities:["structured-output"],detail:"strict JSON generated"}));const stage=await evaluateRuntimeReadiness({repository,governance,designTemplates,snapshot,stage:"brief"});assert.equal(stage.items.find(item=>item.key==="text")?.ready,true);assert.equal(stage.missing.some(item=>item.key==="brief.assistant"),true);});

test("legacy prompt bindings without content hashes remain readable but are not runnable",async()=>{const repository=new InMemoryCourseForgeRepository(),governance=new InMemoryProviderGovernanceStore(),designTemplates=new InMemoryDesignTemplateStore(),actor=crypto.randomUUID(),prompt=PromptVersionV1Schema.parse({schemaVersion:"1",promptVersionId:crypto.randomUUID(),promptKey:"brief.assistant",version:"v1",description:"legacy",template:"safe",status:"published",createdAt:new Date(0).toISOString(),createdBy:actor,publishedAt:new Date(0).toISOString(),inactiveAt:null});await repository.createPromptVersion(prompt);const snapshot={schemaVersion:"1" as const,snapshotId:crypto.randomUUID(),capturedAt:new Date().toISOString(),capturedBy:actor,providerBindings:[],promptBindings:[{promptKey:prompt.promptKey,promptVersionId:prompt.promptVersionId,version:prompt.version}],pronunciationLexiconBinding:null,qaPolicyBinding:null};const readiness=await evaluateRuntimeReadiness({repository,governance,designTemplates,snapshot,stage:"brief"});assert.equal(readiness.status,"not_runnable");assert.equal(readiness.missing.find(item=>item.key==="brief.assistant")?.code,"legacy_prompt_binding_without_hash");});
