import assert from "node:assert/strict";
import test from "node:test";
import sharp from "sharp";
import { CONTRACT_VERSION, type PromptVersionV1, type ProviderConfigVersionV1 } from "@courseforge/contracts";
import { InMemoryArtifactBlobStore } from "./artifacts.js";
import { persistImageAsset } from "./image-assets.js";
import { InMemoryCourseForgeRepository } from "./repositories.js";
import { runVisualAnalysis } from "./visual-analysis.js";

const projectId = "22222222-2222-4222-8222-222222222222"; const actor = { schemaVersion: CONTRACT_VERSION, userId: "11111111-1111-4111-8111-111111111111", email: "editor@example.test", displayName: "Editor", role: "course_editor" as const };
async function fixture(settings: Record<string, unknown> = { enabled: true, allowedOrigins: ["https://vision.example.test"], timeoutMs: 1000 }, secretRefs: Record<string,string> = { api: "env://VISION_KEY" }) {
  const repository = new InMemoryCourseForgeRepository();await repository.saveProject({schemaVersion:"1",projectId,ownerId:actor.userId,dataPolicy:{schemaVersion:"1",mode:"internal",classification:"internal"},brief:{schemaVersion:"1",title:"内部培训",idea:"内部材料",audience:"员工",durationMinutes:20,objectives:["学习"],background:"",locale:"zh-CN",sourceArtifactIds:[]},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}); const blobs = new InMemoryArtifactBlobStore(); const bytes = await sharp({ create: { width: 2, height: 2, channels: 3, background: "white" } }).png().toBuffer(); const asset = await persistImageAsset(repository, blobs, projectId, actor, bytes, "image/png", { displayName: "图", originalFilename: "x.png", licenseStatus: "company-owned" });
  const config: ProviderConfigVersionV1 = { schemaVersion: "1", configId: crypto.randomUUID(), kind: "multimodal", providerId: "vision", version: "v1", displayName: "Vision", endpoint: "https://vision.example.test/v1/chat/completions", model: "vision-1", capabilities: [], settings: {...settings,dataBoundary:"internal",internalAllowedOrigins:["https://vision.example.test"]} as never, secretRefs, status: "published", createdAt: new Date().toISOString(), createdBy: actor.userId, publishedAt: new Date().toISOString(), inactiveAt: null };
  const prompt: PromptVersionV1 = { schemaVersion: "1", promptVersionId: crypto.randomUUID(), promptKey: "visual.analysis", version: "v1", description: "图片分析结构化输出", template: "分析 {{assetCount}} 张培训图片；仅输出JSON对象，包含summary字符串以及ocrHints、chartInsights、risks字符串数组。结论只作非权威建议，不判断版权归属。", status: "published", createdAt: new Date().toISOString(), createdBy: actor.userId, publishedAt: new Date().toISOString(), inactiveAt: null };
  await repository.createProviderConfig(config); await repository.createPromptVersion(prompt); const snapshot = await repository.captureRuntimeConfigSnapshot(crypto.randomUUID(), new Date().toISOString(), actor.userId); return { repository, blobs, asset, snapshot };
}
test("visual analysis is explicit, governed by a published prompt, structured and content addressed", async () => { const f = await fixture(); let requestBody = ""; const fetch = async (_url: URL | string, init?: RequestInit) => { requestBody = String(init?.body); return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify({ summary: "清晰", ocrHints: [], chartInsights: [], risks: ["非权威"] }) } }] }), { status: 200 }); }; const result = await runVisualAnalysis(f.repository, f.blobs, projectId, f.snapshot.snapshotId, [f.asset.assetId], { fetch, secrets:{resolve:async()=>"placeholder"} }); assert.match(requestBody, /分析 1 张培训图片/); assert.equal(result.analysis.authority, "non-authoritative-ai-assistance"); assert.equal(result.analysis.result.summary, "清晰"); });
test("origin is checked before secret resolution and redirects fail closed", async () => { let resolved = 0; const bad = await fixture({ enabled: true, allowedOrigins: ["https://other.example.test"] }, { api: "env://VISION_KEY" }); await assert.rejects(runVisualAnalysis(bad.repository, bad.blobs, projectId, bad.snapshot.snapshotId, [bad.asset.assetId], { secrets: { resolve: async () => { resolved++; return "value"; } } }), /multimodal_invalid/); assert.equal(resolved, 0); const f = await fixture(); await assert.rejects(runVisualAnalysis(f.repository, f.blobs, projectId, f.snapshot.snapshotId, [f.asset.assetId], { secrets:{resolve:async()=>"placeholder"},fetch: async () => new Response(null, { status: 302 }) }), /multimodal_upstream/); });
test("stream response ceiling and timeout fail closed", async () => { const f = await fixture(); await assert.rejects(runVisualAnalysis(f.repository, f.blobs, projectId, f.snapshot.snapshotId, [f.asset.assetId], { secrets:{resolve:async()=>"placeholder"},fetch: async () => new Response(new Uint8Array(256 * 1024 + 1)) }), /response_too_large/); const slow = await fixture({ enabled: true, allowedOrigins: ["https://vision.example.test"], timeoutMs: 1000 }); const fetch = async (_url: URL | string, init?: RequestInit) => await new Promise<Response>((_resolve, reject) => init?.signal?.addEventListener("abort", () => reject(new Error("abort")), { once: true })); await assert.rejects(runVisualAnalysis(slow.repository, slow.blobs, projectId, slow.snapshot.snapshotId, [slow.asset.assetId], { secrets:{resolve:async()=>"placeholder"},fetch }), /multimodal_upstream/); });
