import { createHash } from "node:crypto";
import sharp from "sharp";
import { DeckSpecV1Schema, StyleProfileV1Schema, VisualConfirmationV1Schema, VisualFindingV1Schema, VisualReviewV1Schema, type SessionUserV1 } from "@courseforge/contracts";
import type { z } from "zod";
import { persistBinaryArtifact, type ArtifactBlobStore, type ArtifactMetadataRecord } from "./artifacts.js";
import { findImageAsset, inspectSafeImage } from "./image-assets.js";
import { createSnapshotMultimodalRuntime, findSnapshotPrompt, type PersistedProviderRuntimeOptions } from "./provider-runtime.js";
import { promptContentHash } from "./prompt-catalog.js";
import type { CourseForgeRepository } from "./repositories.js";

type VisualFinding = z.infer<typeof VisualFindingV1Schema>;
const sha256=(value:Uint8Array)=>createHash("sha256").update(value).digest("hex");
const findingId=(value:string)=>`finding-${createHash("sha256").update(value).digest("hex").slice(0,16)}`;
const dataUri=(bytes:Uint8Array)=>`data:image/png;base64,${Buffer.from(bytes).toString("base64")}`;

const STYLE_SCHEMA={type:"object",additionalProperties:false,required:["palette","typography","spacing","layoutPatterns","imageLanguage","chartStyle","decorativeElements","motion","forbiddenPatterns","confidence"],properties:{palette:{type:"object",additionalProperties:{type:"string"}},typography:{type:"object",additionalProperties:{type:"string"}},spacing:{type:"object",additionalProperties:{type:"number"}},layoutPatterns:{type:"array",items:{type:"string"}},imageLanguage:{type:"array",items:{type:"string"}},chartStyle:{type:"array",items:{type:"string"}},decorativeElements:{type:"array",items:{type:"string"}},motion:{type:"array",items:{type:"string"}},forbiddenPatterns:{type:"array",items:{type:"string"}},confidence:{type:"number",minimum:0,maximum:1}}}as const;
const REVIEW_SCHEMA={type:"object",additionalProperties:false,required:["findings"],properties:{findings:{type:"array",items:{type:"object",additionalProperties:false,required:["slideId","category","severity","evidence","suggestion"],properties:{slideId:{type:"string"},category:{type:"string",enum:["style-consistency","hierarchy","readability","balance","repetition","brand-deviation"]},severity:{type:"string",enum:["info","warning"]},evidence:{type:"string"},suggestion:{type:"string"}}}}}}as const;

async function verifiedArtifact(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,artifactId:string,kind:string){const metadata=await repository.findArtifactMetadata(artifactId);if(!metadata||metadata.projectId!==projectId||metadata.kind!==kind)throw new Error("artifact_unavailable");const bytes=await blobs.get(artifactId);if(!bytes||bytes.byteLength!==metadata.byteLength||sha256(bytes)!==metadata.contentHash)throw new Error("artifact_integrity_failed");return{metadata,bytes};}

export async function createStyleProfile(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,actor:SessionUserV1,input:{snapshotId:string;referenceAssetIds:string[];referenceContext?:string;supersedesStyleProfileId?:string},options:PersistedProviderRuntimeOptions={}){
  const {snapshot,provider,config}=await createSnapshotMultimodalRuntime(repository,projectId,input.snapshotId,options);const prompt=await findSnapshotPrompt(repository,snapshot,"visual.style-profile");const binding=snapshot.promptBindings.find(item=>item.promptVersionId===prompt.promptVersionId);if(!binding?.contentHash||binding.contentHash!==promptContentHash(prompt))throw new Error("style_prompt_hash_mismatch");
  const references=[];let total=0;for(const assetId of [...new Set(input.referenceAssetIds)]){const asset=await findImageAsset(repository,blobs,projectId,assetId);if(!asset)throw new Error("reference_unavailable");const bytes=await blobs.get(asset.artifactId);if(!bytes||sha256(bytes)!==asset.contentSha256)throw new Error("reference_integrity_failed");total+=bytes.byteLength;if(total>8*1024*1024)throw new Error("references_too_large");references.push({asset,bytes});}if(references.length<1||references.length>8)throw new Error("invalid_reference_count");
  const rendered=prompt.template.replaceAll("{{referenceContext}}",input.referenceContext??"未提供额外上下文");const observation=(await provider.inspect({prompt:rendered,assets:references.map(({asset,bytes})=>({uri:`data:${asset.mediaType};base64,${Buffer.from(bytes).toString("base64")}`,mediaType:asset.mediaType})),responseSchema:STYLE_SCHEMA},{runId:crypto.randomUUID(),projectId,configurationVersion:input.snapshotId})).observation;
  const raw=observation as Record<string,unknown>;const tokens={palette:raw.palette,typography:raw.typography,spacing:raw.spacing,layoutPatterns:raw.layoutPatterns,imageLanguage:raw.imageLanguage,chartStyle:raw.chartStyle,decorativeElements:raw.decorativeElements,motion:raw.motion,forbiddenPatterns:raw.forbiddenPatterns};const createdAt=new Date().toISOString();const profile=StyleProfileV1Schema.parse({schemaVersion:"1",styleProfileId:crypto.randomUUID(),projectId,snapshotId:input.snapshotId,referenceArtifacts:references.map(({asset})=>({artifactId:asset.artifactId,contentSha256:asset.contentSha256})),prompt:{promptVersionId:prompt.promptVersionId,version:prompt.version,contentHash:binding.contentHash},model:{providerConfigId:config.configId,providerId:config.providerId,name:config.model},tokens,confidence:raw.confidence,authority:"non-authoritative-ai-assistance",supersedesStyleProfileId:input.supersedesStyleProfileId??null,createdAt,createdBy:actor.userId});
  const artifact=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:input.snapshotId,providerId:config.providerId,kind:"visual-style-profile",mediaType:"application/json",content:Buffer.from(JSON.stringify(profile)),sourceArtifactIds:references.map(({asset})=>asset.artifactId),createdAt});return{profile,artifact};
}

/** Persists trusted PNGs returned by the controlled Video Worker. Not exposed as an upload route. */
export async function persistSlideRender(repository:CourseForgeRepository,blobs:ArtifactBlobStore,input:{projectId:string;jobId:string;snapshotId:string;providerId:string;deckArtifactId:string;slideId:string;png:Uint8Array}){
  const deck=await repository.findArtifactMetadata(input.deckArtifactId);if(!deck||deck.projectId!==input.projectId||deck.kind!=="deck-spec")throw new Error("deck_unavailable");const image=await inspectSafeImage(input.png,"image/png");if(image.width!==1920||image.height!==1080)throw new Error("slide_render_dimensions_invalid");return persistBinaryArtifact({repository,blobStore:blobs,projectId:input.projectId,jobId:input.jobId,configurationVersion:input.snapshotId,providerId:input.providerId,kind:"slide-render-png",mediaType:"image/png",content:input.png,sourceArtifactIds:[input.deckArtifactId],revision:Math.max(1,Number.parseInt(input.slideId.replace(/\D+/gu,""),10)||1)});
}

export async function createVisualReview(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,actor:SessionUserV1,input:{snapshotId:string;deckArtifactId:string;slideRenderArtifactIds:string[];styleProfileArtifactId?:string},options:PersistedProviderRuntimeOptions={}){
  const deckSource=await verifiedArtifact(repository,blobs,projectId,input.deckArtifactId,"deck-spec"),deck=DeckSpecV1Schema.parse(JSON.parse(Buffer.from(deckSource.bytes).toString("utf8")));const renders=[];for(const artifactId of [...new Set(input.slideRenderArtifactIds)]){const source=await verifiedArtifact(repository,blobs,projectId,artifactId,"slide-render-png");if(!source.metadata.sourceArtifactIds.includes(input.deckArtifactId))throw new Error("slide_render_stale");renders.push(source);}const deterministic:VisualFinding[]=[];
  renders.sort((left,right)=>left.metadata.revision-right.metadata.revision);if(renders.some((render,index)=>render.metadata.revision!==index+1))throw new Error("slide_render_revision_sequence_invalid");
  for(const [index,slide]of deck.slides.entries()){const render=renders[index];if(!render){deterministic.push({findingId:findingId(`${slide.slideId}:missing`),slideId:slide.slideId,category:"render-failure",severity:"blocker",source:"deterministic",evidence:"当前 Deck 没有对应的逐页 PNG 渲染产物。",suggestion:"使用同一 Deck 哈希重新运行 Video Worker 逐页渲染。"});continue;}try{const dimensions=await inspectSafeImage(render.bytes,"image/png");if(dimensions.width!==1920||dimensions.height!==1080)throw new Error("dimensions");const stats=await sharp(render.bytes).stats();if(stats.channels.slice(0,3).every(channel=>channel.stdev<1))deterministic.push({findingId:findingId(`${slide.slideId}:blank`),slideId:slide.slideId,category:"abnormal-blank",severity:"blocker",source:"deterministic",evidence:"逐页截图接近单一颜色，疑似异常空白。",suggestion:"检查内容渲染、前景色、字体与素材加载。"});}catch{deterministic.push({findingId:findingId(`${slide.slideId}:dimensions`),slideId:slide.slideId,category:"render-failure",severity:"blocker",source:"deterministic",evidence:"PNG 无法完整解码或不是 1920x1080。",suggestion:"检查 Chromium 视口、字体与截图输出。"});}}
  if(renders.length!==deck.slides.length)deterministic.push({findingId:findingId(`${input.deckArtifactId}:count`),slideId:deck.slides[0]!.slideId,category:"render-failure",severity:"blocker",source:"deterministic",evidence:`Deck 有 ${deck.slides.length} 页，但可信截图为 ${renders.length} 页。`,suggestion:"重新渲染全部页面并绑定当前 Deck 哈希。"});
  let style:ReturnType<typeof StyleProfileV1Schema.parse>|undefined;let styleSource:Awaited<ReturnType<typeof verifiedArtifact>>|undefined;if(input.styleProfileArtifactId){styleSource=await verifiedArtifact(repository,blobs,projectId,input.styleProfileArtifactId,"visual-style-profile");style=StyleProfileV1Schema.parse(JSON.parse(Buffer.from(styleSource.bytes).toString("utf8")));}
  const {snapshot,provider,config}=await createSnapshotMultimodalRuntime(repository,projectId,input.snapshotId,options),prompt=await findSnapshotPrompt(repository,snapshot,"visual.deck-review"),binding=snapshot.promptBindings.find(item=>item.promptVersionId===prompt.promptVersionId);if(!binding?.contentHash||binding.contentHash!==promptContentHash(prompt))throw new Error("review_prompt_hash_mismatch");const ai:VisualFinding[]=[];
  for(let offset=0;offset<renders.length;offset+=8){const batch=renders.slice(offset,offset+8),slideIds=deck.slides.slice(offset,offset+8).map(slide=>slide.slideId);const renderedPrompt=prompt.template.replaceAll("{{styleProfileJson}}",JSON.stringify(style?.tokens??{})).replaceAll("{{rubricJson}}",JSON.stringify({version:"courseforge-visual-rubric-v1",slideIds}));const observation=(await provider.inspect({prompt:renderedPrompt,assets:batch.map(({bytes})=>({uri:dataUri(bytes),mediaType:"image/png"})),responseSchema:REVIEW_SCHEMA},{runId:crypto.randomUUID(),projectId,configurationVersion:input.snapshotId})).observation;const raw=(observation as{findings?:unknown}).findings;if(!Array.isArray(raw))throw new Error("visual_review_invalid");for(const [index,value]of raw.entries()){const candidate=value as Record<string,unknown>;if(!slideIds.includes(String(candidate.slideId)))throw new Error("visual_review_slide_mismatch");ai.push({findingId:findingId(`${offset}:${index}:${JSON.stringify(candidate)}`),slideId:String(candidate.slideId),category:candidate.category as VisualFinding["category"],severity:candidate.severity as "info"|"warning",source:"multimodal",evidence:String(candidate.evidence),suggestion:String(candidate.suggestion)});}}
  const createdAt=new Date().toISOString(),review=VisualReviewV1Schema.parse({schemaVersion:"1",visualReviewId:crypto.randomUUID(),projectId,snapshotId:input.snapshotId,deckArtifactId:deckSource.metadata.artifactId,deckContentSha256:deckSource.metadata.contentHash,styleProfileArtifactId:styleSource?.metadata.artifactId??null,rubricVersion:"courseforge-visual-rubric-v1",slides:renders.map((render,index)=>({slideId:deck.slides[index]?.slideId??`unexpected-${index}`,renderArtifactId:render.metadata.artifactId,renderContentSha256:render.metadata.contentHash})),findings:[...deterministic,...ai],deterministicBlockerCount:deterministic.filter(item=>item.severity==="blocker").length,aiWarningCount:ai.filter(item=>item.severity==="warning").length,authority:"non-authoritative-ai-assistance",prompt:{promptVersionId:prompt.promptVersionId,version:prompt.version,contentHash:binding.contentHash},model:{providerConfigId:config.configId,providerId:config.providerId,name:config.model},createdAt,createdBy:actor.userId});const artifact=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:input.snapshotId,providerId:config.providerId,kind:"visual-review",mediaType:"application/json",content:Buffer.from(JSON.stringify(review)),sourceArtifactIds:[input.deckArtifactId,...renders.map(item=>item.metadata.artifactId),...(styleSource?[styleSource.metadata.artifactId]:[])],createdAt});return{review,artifact};
}

export async function latestVisualReview(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string){const candidates=(await repository.listArtifactMetadata(projectId)).filter(item=>item.kind==="visual-review").sort((a,b)=>b.createdAt.localeCompare(a.createdAt));for(const metadata of candidates){try{const source=await verifiedArtifact(repository,blobs,projectId,metadata.artifactId,"visual-review");return{review:VisualReviewV1Schema.parse(JSON.parse(Buffer.from(source.bytes).toString("utf8"))),artifact:metadata};}catch{/* Skip corrupt/tombstoned candidates. */}}return undefined;}

export async function confirmVisualReview(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,actor:SessionUserV1,input:{visualReviewArtifactId:string;note:string}){const source=await verifiedArtifact(repository,blobs,projectId,input.visualReviewArtifactId,"visual-review"),review=VisualReviewV1Schema.parse(JSON.parse(Buffer.from(source.bytes).toString("utf8")));if(review.deterministicBlockerCount>0)throw new Error("visual_blockers_present");const deck=await repository.findArtifactMetadata(review.deckArtifactId);if(!deck||deck.contentHash!==review.deckContentSha256)throw new Error("visual_review_stale");for(const slide of review.slides){const render=await repository.findArtifactMetadata(slide.renderArtifactId);if(!render||render.contentHash!==slide.renderContentSha256)throw new Error("visual_review_stale");}const confirmedAt=new Date().toISOString(),confirmation=VisualConfirmationV1Schema.parse({schemaVersion:"1",visualConfirmationId:crypto.randomUUID(),projectId,visualReviewArtifactId:source.metadata.artifactId,deckArtifactId:review.deckArtifactId,deckContentSha256:review.deckContentSha256,slideRenderHashes:review.slides.map(slide=>slide.renderContentSha256),note:input.note,confirmedAt,confirmedBy:actor.userId});const artifact=await persistBinaryArtifact({repository,blobStore:blobs,projectId,jobId:crypto.randomUUID(),configurationVersion:review.snapshotId,providerId:"human-visual-confirmation-v1",kind:"visual-confirmation",mediaType:"application/json",content:Buffer.from(JSON.stringify(confirmation)),sourceArtifactIds:[source.metadata.artifactId,review.deckArtifactId,...review.slides.map(slide=>slide.renderArtifactId)],createdAt:confirmedAt});return{confirmation,artifact};}

export async function findCurrentVisualConfirmation(repository:CourseForgeRepository,blobs:ArtifactBlobStore,projectId:string,deckArtifactId:string,deckHash:string){const candidates=(await repository.listArtifactMetadata(projectId)).filter(item=>item.kind==="visual-confirmation"&&item.sourceArtifactIds.includes(deckArtifactId)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));for(const metadata of candidates){try{const source=await verifiedArtifact(repository,blobs,projectId,metadata.artifactId,"visual-confirmation"),value=VisualConfirmationV1Schema.parse(JSON.parse(Buffer.from(source.bytes).toString("utf8")));if(value.deckContentSha256===deckHash)return{confirmation:value,artifact:metadata};}catch{/* Invalid confirmations never satisfy publication. */}}return undefined;}
